export const txt_info_participate_in_challenge_success = "Вы были добавлены, теперь вы можете загрузить видео.";
export const txt_not_exist_money_participate_challenge = "Извините, у вас не достаточно средств что бы учавстовать в челлендже";
export const txt_service_busy = "Извините сервис не работает. Пожалуйста попробуйте позже.";
export const txt_info_add_judge_failed = "Вы не можете учавстовать";
export const txt_info_to_big_file = "Видео не загружено, размер должен не привышать 200 MB";
export const txt_info_uplaod_success = "Видео было добавлено";
export const txt_info_uplaod_failed = "Видео не удалось загрузить, пожалйста попробуйте позже";
export const txt_info_set_winner_success = "Пользователь был назначен победителем";
export const txt_add_challenge_success = "Челлендж был создан";
export const txt_not_exist_money_add_challenge = "Извините, у вас не достаточно средств";
export const types_txt = ["Workout"];
export const status_support_txt = ["Open", "Closed"];
export const rank_txt = ["Junior", "Middle", "Senior"];
export const support_subjects = ["Comments and suggestions", "Report user"];
export const hit_support_input = "Введите описание вопроса...";
export const txt_support_add_successful = "Ваше особщение было отправлено успешно."
export const txt_error_send_message_chat = "Невозможно отправить сообщение";
export const txt_close_support_item = "Что бы закрыть тему нажмите сдесь";
export const txt_closed_support_success = "Тикет был закрыт";